Databases:
  # tell pyannote.database where to find AMI wav files.
  # {uri} is a placeholder for the session name (eg. ES2004c).
  # you might need to update this line to fit your own setup.
  AMI: ./{uri}.Mix-Headset.wav

Protocols:
  AMI:
    SpeakerDiarization:
      only_words:
        train:
            uri: ./list.txt
            annotation: ./{uri}.rttm
            annotated: ./{uri}.uem
        development:
            uri: ./list.txt
            annotation: ./{uri}.rttm
            annotated: ./{uri}.uem
        test:
            uri: ./list.txt
            annotation: ./{uri}.rttm
            annotated: ./{uri}.uem
 